FORMAT: 1A
HOST: http://bankAccountBalanceAgain.apiblueprint.org/

# BankAccountBalanceAgain

A simple API to allowing retrieval of bank account balance information

## Balance Collection [/accountBalanceAgain11]

### Get Balance Again  [GET]

Get account balance.

+ Request (application/json)

        {"accountNr": "12345678",
         "bankCode": "AIB"}

+ Response 200 (application/json)

    + Headers

            Location: /accountBalance/2

    + Body

        {"accountNr" : "12345678",
         "bankName" : "Allied Irish Banks plc.",
         "branch" : "Artane Roundabout, Dublin 5",
         "custFirstName" : "Niall",
         "custLastName" : "Commiskey",
         "custEmail" : "n@c.com",
         "balance" : 23000,
         "dateLastTransaction": "31st Oct. 2017"
  }